### ISSUE TITLE
Installer fails on Debian

### ISSUE THREAD

**Issue by WayneManion** [ballaswag/guppyflo#2]
The installer script fails on my Debian Klipper host. Here are the last few lines of output from the installer script:

```Configuring GuppyFLO services 
Restarting GuppyFLO service 
sh: 38: service: not found
Successfully installed GuppyFLO 
```
I believe this is because the script uses Ubuntu's 'service' wrapper for systemd. I believe the script can be modified to use systemd's 'systemctl' command instead of 'service'.

**Comment by ballaswag** [comment]
Thanks for the report. I have only tested on Ubuntu. Will setup a Debian docker to test. For what is worth, you should have necessary files extracted in your home for under guppyflo. You’ll just need to setup the service manually for now until I fix the installer. Make sure the service use the guppyflo dir as the working directory.

**Comment by WayneManion** [comment]
I edited installer.sh and ran it on my Debian Klipper host. It worked. These changes should still work with Ubuntu since both use systemd. 

I made a pull request for these changes.

**Comment by ballaswag** [comment]
Thanks for the fix!
